#################################### common config : ####################################
spring:
  application:
    name: common-account
  datasource:
    url: jdbc:mysql://adev.top:3306/adev-account?serverTimezone=UTC
    username: root
    password: 239ea79e9e2a61df
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #important! Don't change!
      use-new-id-generator-mappings: true
    show-sql: false
  redis:
    host: adev.top
    port: 6379
    password: adev.top
# 应用服务web访问端口
server:
  port: 8081

# eureka客户端配置
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
    # 实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      # 注册中心地址
      defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
      